# Generated by Django 4.0.6 on 2022-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_modifiergroup_product_status_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(to='main.modifiergroup'),
        ),
    ]
